In [1]:
import pandas as pd

In [ ]:
data = {'coluna_1':[1.5,2.0,1.7,2.2,1.9],
        'coluna_2':[10.0,12.0,11.5,13.0,11.0],
        'coluna_3':[0,1,0,1,0],
        'coluna_4':[1,0,1,1,0],
        'coluna_5':[20.5,25.5,22.0,27.0,23.0]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
print(df)

   coluna_1  coluna_2  coluna_3  coluna_4  coluna_5
0       1.5      10.0         0         1      20.5
1       2.0      12.0         1         0      25.5
2       1.7      11.5         0         1      22.0
3       2.2      13.0         1         1      27.0
4       1.9      11.0         0         0      23.0

In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
origem = '/content/drive/My Drive/Data/COMEXSTAT/'

In [5]:
arquivo_1 = origem + 'EXP_2025.csv'
arquivo_2 = origem + 'EXP_2026.csv'
ncm = origem + 'NCM.csv'
pais = origem + 'PAIS.csv'
vias = origem + 'VIA.csv'
urf = origem + 'URF.csv'

In [6]:
exp25 = pd.read_csv(arquivo_1,low_memory=False,sep=";",encoding='UTF-8')
exp26 = pd.read_csv(arquivo_2,low_memory=False,sep=";",encoding='UTF-8')
expncm = pd.read_csv(ncm,low_memory=False,sep=";",encoding='latin1')
exppais = pd.read_csv(pais,low_memory=False,sep=";",encoding='latin1')
expvias = pd.read_csv(vias,low_memory=False,sep=";",encoding='latin1')
expurf = pd.read_csv(urf,low_memory=False,sep=";",encoding='latin1')

In [ ]:
exp25 = pd.read_csv(arquivo_1,low_memory=False,sep=";",encoding='UTF-8')

In [7]:
exp25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1709746 entries, 0 to 1709745
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_NCM      int64
 3   CO_UNID     int64
 4   CO_PAIS     int64
 5   SG_UF_NCM   object
 6   CO_VIA      int64
 7   CO_URF      int64
 8   QT_ESTAT    int64
 9   KG_LIQUIDO  int64
 10  VL_FOB      int64
dtypes: int64(10), object(1)
memory usage: 143.5+ MB

In [8]:
exp26.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 982645 entries, 0 to 982644
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   CO_ANO      982645 non-null  int64
 1   CO_MES      982645 non-null  int64
 2   CO_NCM      982645 non-null  int64
 3   CO_UNID     982645 non-null  int64
 4   CO_PAIS     982645 non-null  int64
 5   SG_UF_NCM   982645 non-null  object
 6   CO_VIA      982645 non-null  int64
 7   CO_URF      982645 non-null  int64
 8   QT_ESTAT    982645 non-null  int64
 9   KG_LIQUIDO  982645 non-null  int64
 10  VL_FOB      982645 non-null  int64
dtypes: int64(10), object(1)
memory usage: 82.5+ MB

In [9]:
expncm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13746 entries, 0 to 13745
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CO_NCM          13746 non-null  int64
 1   CO_UNID         13746 non-null  int64
 2   CO_SH6          13746 non-null  int64
 3   CO_PPE          13440 non-null  float64
 4   CO_PPI          13440 non-null  float64
 5   CO_FAT_AGREG    13724 non-null  float64
 6   CO_CUCI_ITEM    13746 non-null  object
 7   CO_CGCE_N3      13746 non-null  int64
 8   CO_SIIT         13440 non-null  float64
 9   CO_ISIC_CLASSE  13746 non-null  int64
 10  CO_EXP_SUBSET   13438 non-null  float64
 11  NO_NCM_POR      13746 non-null  object
 12  NO_NCM_ESP      13746 non-null  object
 13  NO_NCM_ING      13746 non-null  object
dtypes: float64(5), int64(5), object(4)
memory usage: 1.5+ MB

In [10]:
exp_final = pd.concat([exp25,exp26], ignore_index=True)
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2692391 entries, 0 to 2692390
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_NCM      int64
 3   CO_UNID     int64
 4   CO_PAIS     int64
 5   SG_UF_NCM   object
 6   CO_VIA      int64
 7   CO_URF      int64
 8   QT_ESTAT    int64
 9   KG_LIQUIDO  int64
 10  VL_FOB      int64
dtypes: int64(10), object(1)
memory usage: 226.0+ MB

In [ ]:
exp_final.head(5)

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2025,8,71039900,19,687,RS,4,817700,61690,13,203
1,2025,12,2071412,10,741,SC,1,817800,83835,83835,111324
2,2025,11,33059000,10,767,SP,4,817600,792,753,22012
3,2025,11,56031330,10,845,SP,7,1017701,2437,2437,8458
4,2025,6,21069090,10,365,SP,1,817800,4800,4800,17304

In [ ]:
exp_final.tail(5)

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
2692386,2026,4,25030090,10,63,SP,7,1017500,5000,5000,4250
2692387,2026,3,90261011,11,249,SP,4,817600,78,4290,70067
2692388,2026,2,72091600,10,493,SC,4,817700,4,4,93
2692389,2026,3,97039000,11,521,SP,4,817600,19,25,2501
2692390,2026,1,85395100,11,149,SP,4,817700,7,17,7066

In [ ]:
exppais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CO_PAIS        281 non-null    int64
 1   CO_PAIS_ISON3  281 non-null    int64
 2   CO_PAIS_ISOA3  281 non-null    object
 3   NO_PAIS        281 non-null    object
 4   NO_PAIS_ING    281 non-null    object
 5   NO_PAIS_ESP    281 non-null    object
dtypes: int64(2), object(4)
memory usage: 13.3+ KB

In [14]:
exp_final = exp_final.merge(exppais[['CO_PAIS','NO_PAIS']], on='CO_PAIS', how='left')

In [ ]:
exp_final.head(5)

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB,NO_PAIS
0,2025,8,71039900,19,687,RS,4,817700,61690,13,203,El Salvador
1,2025,12,2071412,10,741,SC,1,817800,83835,83835,111324,Singapura
2,2025,11,33059000,10,767,SP,4,817600,792,753,22012,Suíça
3,2025,11,56031330,10,845,SP,7,1017701,2437,2437,8458,Uruguai
4,2025,6,21069090,10,365,SP,1,817800,4800,4800,17304,Indonésia

In [11]:
exp_final = exp_final.merge(expncm[['CO_NCM','NO_NCM_POR']], on='CO_NCM', how='left')

In [12]:
exp_final.head(5)

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB,NO_NCM_POR
0,2025,8,71039900,19,687,RS,4,817700,61690,13,203,Outras pedras preciosas (exceto diamantes) ou ...
1,2025,12,2071412,10,741,SC,1,817800,83835,83835,111324,Coxas com sobrecoxas não desossadas de galinha...
2,2025,11,33059000,10,767,SP,4,817600,792,753,22012,Outras preparações capilares
3,2025,11,56031330,10,845,SP,7,1017701,2437,2437,8458,"Falsos tecidos de poliéster, de peso superior ..."
4,2025,6,21069090,10,365,SP,1,817800,4800,4800,17304,Outras preparações alimentícias

In [15]:
coluna = 'NO_PAIS'
CP = exp_final[coluna].value_counts().sort_values(ascending=False)
print(f'Total de operações {coluna}:')
print(CP)

Total de operações NO_PAIS:
NO_PAIS
Paraguai                     172240
Argentina                    168833
Estados Unidos               151029
Uruguai                      114930
Panamá                       113902
                              ...
Christmas (Navidad), Ilha         2
Eritreia                          1
Santa Helena                      1
Coreia do Norte                   1
Saara Ocidental                   1
Name: count, Length: 247, dtype: int64

In [16]:
exp_final.to_csv(origem+'exp_final.csv', index=False)

In [17]:
#tentativa 1 - as informações não foram alocadas nas posições exigidas
colunames = 'CO_MES'
CM = exp_final[colunames].value_counts().sort_index(ascending=True)
print(f'Total de operações {colunames}:')
print(CM)

Total de operações CO_MES:
CO_MES
1     252133
2     245468
3     291825
4     288328
5     279327
6     290112
7     302052
8     143937
9     148403
10    152457
11    145897
12    152452
Name: count, dtype: int64

In [18]:
#tentativa 2 - as informações foram alocadas na posição exigida (meses no eixo x e total de importações no )
meses = {'Janeiro':[252133],
        'Fevereiro':[245468],
        'Março':[291825],
        'Abril':[288328],
        'Maio':[279327],
        'Junho':[290112],
        'Julho':[302052],
        'Agosto':[143937],
        'Setembro':[148403],
        'Outubro':[152457],
        'Novembro':[145897],
        'Dezembro':[152452]}

In [19]:
dm = pd.DataFrame(meses)

In [20]:
print(dm)

   Janeiro  Fevereiro   Março   Abril    Maio   Junho   Julho  Agosto  \
0   252133     245468  291825  288328  279327  290112  302052  143937

   Setembro  Outubro  Novembro  Dezembro
0    148403   152457    145897    152452